<?php use Phalcon\Tag; ?>

	<h2>Add new point</h2>
<?= Tag::form( array( "voting_point/add", "class" => "form-horizontal" ) ) ?>
	<div class="form-group">
		<label class="control-label col-sm-2" for="name">Name</label>

		<div class="col-sm-10">
			<?= Tag::textField( array( "name", "class" => "form-control" ) ) ?>
		</div>
	</div>
	<div class="form-group">
		<label class="control-label col-sm-2" for="description">Descritpion</label>

		<div class="col-sm-10">
			<?= Tag::textArea( array( "description", "class" => "form-control" ) ) ?>
		</div>
	</div>
	<div class="form-group">
		<label class="control-label col-sm-2" for="date">Date</label>

		<div class="col-sm-10">
			<?= Tag::textField( array( "date", "id" => "dp1", "class" => "form-control" ) ); ?>
		</div>
	</div>
	<div class="form-group">
		<label class="control-label col-sm-2" for="tags">Tags</label>

		<div class="col-sm-10">
			<?= Tag::select( array(
				                 "tags[]",
				                 "multiple" => "multiple",
				                 Tags::find( array( "order" => "name" ) ),
				                 "using" => array( "id", "name" ),
				                 "class" => "form-control",
				                 "id" => "tags"
			                 ) ); ?>
		</div>
	</div>
	<div class="form-group">

		<div class="col-sm-offset-2 col-sm-10">
			<?= Tag::submitButton( array( "Submit", "class" => "btn btn-success" ) ) ?>
		</div>
	</div>
	</form>
<?= Tag::javascriptInclude( "js/script.js" ) ?>