<?php use Phalcon\Tag; ?>

	<h2>Points</h2>

	<table class="table table-hover">
		<caption>Voting points</caption>
		<thead>
		<tr>
			<th>Name</th>
			<th>Description</th>
			<th>Date</th>
		</tr>
		</thead>
		<tbody>
		<?php foreach( $points as $entry ){?>
			<tr>
				<td><?= $entry->getName() ?></td>
				<td><?= $entry->getDescription() ?></td>
				<td><?= $entry->getDate() ?></td>
			</tr>
		<?php }?>
	</table>

<?= Tag::linkTo( "voting_point/add", "Add new" ) ?>