<?php use Phalcon\Tag; ?>

	<h2>Add new voting history</h2>

<?= Tag::form( array( "voting_history/add", "class" => "form-horizontal", "role" => "form" ) ); ?>
	<div class="form-group">
		<label for="point" class="col-sm-2 control-label">Point</label>

		<div class="col-sm-10">
			<?= Tag::select( array(
				                 "point",
				                 VotingPoint::find( array(
					                                    "order" => "date DESC, name",
					                                    'columns' => array( 'id', "name" ),
				                                    ) ),
				                 "using" => array( "id", "name" ),
				                 "class" => "form-control",
				                 "useEmpty" => true ) ) ?>
		</div>
	</div>

	<div class="form-group">
		<label for="person" class="col-sm-2 control-label">Person</label>

		<div class="col-sm-10">
			<?= Tag::select( array(
				                 "person",
				                 Person::find( array(
					                               "is_active = true",
					                               "order" => "last_name, first_name",
					                               'columns' => array( "id",
					                                                   " CONCAT( first_name, ' ', last_name ) as fullname" ),
				                               ) ),
				                 "using" => array( "id", "fullname" ),
				                 "class" => "form-control",
				                 "useEmpty" => true
			                 ) ) ?>
		</div>
	</div>
	<div class="form-group">
		<label for="voted" class="col-sm-2 control-label">Voted</label>

		<div class="col-sm-10">
			<?= VotingOptions::votingOptionsSelect( array( "voted", "class" => "form-control", "useEmpty" => true ) ) ?>
		</div>
	</div>
	<div class="form-group">
		<div class="col-sm-offset-2 col-sm-10">

			<?= Tag::submitButton( array( "Submit", "class" => "btn btn-success" ) ) ?>
		</div>
	</div>
	</form>
<?= Tag::javascriptInclude( "js/script.js" ) ?>