<?php use Phalcon\Tag; ?>

<h2>Edit voting history</h2>

<?= Tag::form( array( "voting_history/edit/" . $history->getId(), "class" => "form-horizontal", "role" => "form" ) ); ?>
<div class="form-group">
	<label for="point" class="col-sm-2 control-label">Point</label>

	<div class="col-sm-10">
		<p class="form-control-static"><?= $history->votingPoint->getName() ?></p>
	</div>
</div>

<div class="form-group">
	<label for="person" class="col-sm-2 control-label">Person</label>

	<div class="col-sm-10">
		<p class="form-control-static"><?= $history->person->getName() ?></p>
	</div>
</div>
<div class="form-group">
	<label for="voted" class="col-sm-2 control-label">Voted</label>

	<div class="col-sm-10">
		<?= VotingOptions::votingOptionsSelect( array( "voted",
		                                               "class" => "form-control",
		                                               "selected" => $history->getVoted() ) ) ?>
	</div>
</div>
<div class="form-group">
	<div class="col-sm-offset-2 col-sm-10">

		<?= Tag::submitButton( array( "Submit", "class" => "btn btn-success" ) ) ?>
	</div>
</div>
</form>