<?php use Phalcon\Tag; ?>

<?= Tag::form( array( "person/add", "class" => "form-horizontal", "role" => "form" )); ?>
<div class="form-group">
	<label for="name" class="col-sm-2 control-label">Name</label>
	<div class="col-sm-10">
	<?= Tag::textField( array( "name", "class"=>"form-control" )) ?>
		</div>

	<label for="surname" class="col-sm-2 control-label">Surname</label>
	<div class="col-sm-10">
	<?= Tag::textField( array( "surname", "class"=>"form-control" )) ?>
	</div>

	<div class="form-group">
		<div class="col-sm-offset-2 col-sm-10">
			<?= Tag::submitButton( array( "Submit", "class" => "btn btn-default" )) ?>
		</div>
	</div>

</div>
</form>