<?php use Phalcon\Tag; ?>

	<table class="table table-hover">
		<caption>Persons</caption>
		<thead>
		<tr>
			<th>First Name</th>
			<th>Last Name</th>
			<th>Actions</th>
		</tr>
		</thead>
		<tbody>
<?php foreach( $users as $user ){?>
<tr>
	<td><?= $user->getFirstName() ?></td>
	<td><?= $user->getLastName() ?></td>
	<td>
		<?= Tag::linkTo( "person/view/" . $user->getId(), '<span class="glyphicon glyphicon-eye-open"></span>' ) ?>
		&nbsp;
		<?= Tag::linkTo( "person/edit/" . $user->getId(), '<span class="glyphicon glyphicon-pencil"></span>' ) ?>
	</td>
</tr>
<?php }?>
</table>
<?= Tag::linkTo( "person/add", "Add new" ) ?>