<?php use Phalcon\Tag; ?>

<h2>Add new tag</h2>
<?= Tag::form( array( "tags/add", "class" => "form-horizontal" ) ) ?>
<div class="form-group">
	<label class="control-label col-sm-2" for="name">Name</label>

	<div class="col-sm-10">
		<?= Tag::textField( array( "name", "class" => "form-control" ) ) ?>
	</div>
</div>
<div class="form-group">
	<div class="col-sm-offset-2 col-sm-10">
		<?= Tag::submitButton( array( "Submit", "class" => "btn btn-success" ) ) ?>
	</div>
</div>
</form>