<?php use Phalcon\Tag; ?>

<h2>Tags</h2>

<p>
	<?= Tag::linkTo( "tags/add", '<button type="button" class="btn btn-default"><span class="glyphicon glyphicon-plus"></span> Add new</button>' ) ?>
</p>

<table class="table table-hover">
	<thead>
	<tr>
		<th>Name</th>
		<th>Actions</th>
	</tr>
	</thead>
	<tbody>
	<?php foreach( $tags as $entry ){ ?>
		<tr>
			<td><?= $entry->getName() ?></td>
			<td>
				<?= Tag::linkTo( "tags/view/" . $entry->getId(), '<span class="glyphicon glyphicon-eye-open"></span>' ) ?>
				&nbsp;
				<?= Tag::linkTo( "tags/edit/" . $entry->getId(), '<span class="glyphicon glyphicon-pencil"></span>' ) ?>
			</td>
		</tr>
	<?php } ?>
</table>
<script>
	$( 'table' ).filterTable();
</script>
